#!/usr/bin/env python3
"""build-hot.py — generate a dev_wiki "hot pages" digest.

Ranks content pages under <vault>/wiki/ and writes a compact digest to
<vault>/hot.md (vault root — deliberately outside wiki/, so it stays invisible
to keyword search, /wiki-lint, and the HTTP files API; the SessionStart hook
reads it directly from disk).

Ranking signal (no external deps — stdlib only):
  - recency      : frontmatter `updated:` (YYYY-MM-DD), file mtime fallback.
  - centrality   : wikilink degree (inbound + outbound [[links]]).
  - frequency    : NOT YET — page-access counts need P4's retrieval-log
                   (wiki/_meta/retrieval-log.jsonl). Wired as a 0-weight slot
                   below so it slots in without a rewrite.

Usage:
  build-hot.py [--vault DIR] [--top N] [--out FILE]
Defaults: --vault $CLAUDE_PROJECT_DIR or cwd, --top 20, --out <vault>/hot.md.
Prints a one-line summary to stderr.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date, datetime
from pathlib import Path

STRUCTURAL = {"index", "log", "overview", "purpose", "schema"}
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)")

# Ranking weights. frequency is 0 until the retrieval-log exists (P4).
W_RECENCY = 0.6
W_CENTRALITY = 0.4
W_FREQUENCY = 0.0


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal scalar frontmatter parser — no yaml dependency. Returns the
    few fields we rank/display by; lists and nested values are ignored."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    out: dict[str, str] = {}
    for line in text[3:end].splitlines():
        m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val and val[0] in "\"'" and val[-1:] == val[0]:
            val = val[1:-1]
        out[key] = val
    return out


class Page:
    __slots__ = ("pid", "rel", "title", "ptype", "bc", "summary", "updated",
                 "mtime", "out_links", "degree", "score")

    def __init__(self, pid, rel, fm, mtime, out_links):
        self.pid = pid
        self.rel = rel
        self.title = fm.get("title") or pid
        self.ptype = fm.get("type") or "?"
        self.bc = (fm.get("bc") or "general").strip().lower()
        self.summary = fm.get("summary") or ""
        self.updated = fm.get("updated") or ""
        self.mtime = mtime
        self.out_links = out_links
        self.degree = len(out_links)
        self.score = 0.0


def collect_pages(wiki: Path) -> list[Page]:
    pages: list[Page] = []
    for path in sorted(wiki.rglob("*.md")):
        pid = path.stem
        if pid in STRUCTURAL:
            continue
        # _meta/*.md (bc-readme) are kept; _meta/*.yaml are not .md so excluded.
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        fm = parse_frontmatter(text)
        links = {m.strip() for m in WIKILINK_RE.findall(text) if m.strip()}
        links.discard(pid)
        try:
            mtime = path.stat().st_mtime
        except OSError:
            mtime = 0.0
        pages.append(Page(pid, str(path.relative_to(wiki.parent)), fm, mtime, links))
    return pages


def score_pages(pages: list[Page], today: date) -> None:
    # Inbound degree: a page linked by many others is central.
    by_id = {p.pid: p for p in pages}
    inbound: dict[str, int] = {p.pid: 0 for p in pages}
    for p in pages:
        for target in p.out_links:
            # resolve loose: exact stem, or slugified
            t = target if target in by_id else target.lower().replace(" ", "-")
            if t in inbound:
                inbound[t] += 1
    for p in pages:
        p.degree += inbound[p.pid]

    def recency_days(p: Page) -> float:
        if p.updated:
            try:
                d = datetime.strptime(p.updated[:10], "%Y-%m-%d").date()
                return max(0.0, (today - d).days)
            except ValueError:
                pass
        if p.mtime:
            return max(0.0, (today - date.fromtimestamp(p.mtime)).days)
        return 9999.0

    days = {p.pid: recency_days(p) for p in pages}
    max_days = max(days.values()) or 1.0
    max_deg = max((p.degree for p in pages), default=0) or 1

    for p in pages:
        recency_norm = 1.0 - (days[p.pid] / max_days)   # newer → 1
        centrality_norm = p.degree / max_deg
        p.score = W_RECENCY * recency_norm + W_CENTRALITY * centrality_norm
        # + W_FREQUENCY * freq_norm  (P4: retrieval-log)


def render(pages: list[Page], top: int, today: date) -> str:
    ranked = sorted(pages, key=lambda p: p.score, reverse=True)[:top]
    lines = [
        "---",
        "# AUTO-GENERATED by wiki-toolkit/scripts/build-hot.py — do not edit by hand.",
        "---",
        "",
        f"# 🔥 dev_wiki 热点页 ({today.isoformat()})",
        "",
        f"> 按「最近更新 + 链接中心度」排序的前 {len(ranked)} 页。"
        "访问频次维度待 P4 召回日志接入。",
        "",
    ]
    by_bc: dict[str, list[Page]] = {}
    for p in ranked:
        by_bc.setdefault(p.bc, []).append(p)
    for bc in sorted(by_bc):
        lines.append(f"## {bc}")
        for p in by_bc[bc]:
            summ = p.summary.strip().splitlines()[0] if p.summary.strip() else ""
            if len(summ) > 100:
                summ = summ[:100].rstrip() + "…"
            tail = f" — {summ}" if summ else ""
            lines.append(f"- **{p.title}** (`{p.ptype}` · `{p.rel}`){tail}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate dev_wiki hot.md")
    ap.add_argument("--vault", default=os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    ap.add_argument("--top", type=int, default=20)
    ap.add_argument("--out", default=None)
    # --today lets tests pin "now"; default is the real date.
    ap.add_argument("--today", default=None, help="YYYY-MM-DD override for testing")
    args = ap.parse_args(argv)

    vault = Path(args.vault)
    wiki = vault / "wiki"
    if not wiki.is_dir():
        print(f"build-hot: no wiki/ under {vault} — nothing to do", file=sys.stderr)
        return 0

    today = (datetime.strptime(args.today, "%Y-%m-%d").date()
             if args.today else date.today())
    pages = collect_pages(wiki)
    if not pages:
        print("build-hot: no content pages found", file=sys.stderr)
        return 0
    score_pages(pages, today)
    out_path = Path(args.out) if args.out else vault / "hot.md"
    out_path.write_text(render(pages, args.top, today), encoding="utf-8")
    print(f"build-hot: wrote {min(args.top, len(pages))}/{len(pages)} pages → {out_path}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
